DeveloperAcademy-POSTECH/MacC-Team-IKU

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/Data/Eye.swift

- 전역에서 사용할 enum인 Eye를 추가했습니다.
- 앞으로 left, right를 잘 선택해서 작업하시기 바랍니다.
- 별도의 Test 불필요

[D1] enum Eye 추가

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/Data/DataPlaceholder.swift
IKU/IKU/Data/MeasurementResult.swift

- 측정 결과를 저장할 때 저장할 Entity를 만들었습니다.
- 테스트 불필요

[D1] 결과 저장 Entity 생성

---

IKU/IKU/Manager/ARSceneManager.swift
IKU/IKU/Manager/PHPhotoManager.swift
IKU/IKU/Views/SelectWhichEyeView.swift

Remove Enum Eyes

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/Data/Eye.swift
IKU/IKU/Views/StoryView.swift

Add PhotoManager

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/App/SceneDelegate.swift
IKU/IKU/Storyboard/HistoryVC.storyboard
IKU/IKU/Views/ProfileViewController.swift

🔓 open #63 
ProfileUI 구현
단순 UI만 구성하였습니다.
버튼은 연결이 되는지 확인하기 위해서 다른 뷰를 임시로 넣어놨습니다.
width = "250"/>

[D2] ProfileUI 구현

---

IKU/IKU/Views/CoverTestViewController.swift
IKU/IKU/Views/CoverTestViewModel.swift
IKU/IKU/Views/HistoryViewController.swift
IKU/IKU/Views/ResultViewController.swift
IKU/IKU/Views/SelectPhotoViewController.swift
IKU/IKU/Views/ViewModule/IKUChartView.swift

🔐 close #57
🔐 close #62
🔓 open #
- Figma의 UI 업데이트 사항이 일부 반영되었습니다.

[D1] HistoryView UI Update

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/App/SceneDelegate.swift
IKU/IKU/Extension/Double+Extension.swift
IKU/IKU/Manager/ARSceneManager.swift
IKU/IKU/Views/CoverTestViewController.swift
IKU/IKU/Views/HistoryViewController.swift
IKU/IKU/Views/ResultViewController.swift
IKU/IKU/Views/SelectPhotoViewController.swift
IKU/IKU/Views/StoryView.swift
IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarTouchController.swift
IKU/IKU/Views/ViewModule/IKUCalendarView/IKUCalendarView+Extension.swift

🔐 close #76 
🔐 close #77 
- 검사가 가능하도록 하였습니다.
- 동영상 저장은 가능하지만 기록은 저장되지 않습니다.
- 검사할 눈을 골라 검사를 진행해보시면됩니다.

[D1] 사시 검사 및 각도 계산 결과 표시

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/App/SceneDelegate.swift
IKU/IKU/Views/ProfileViewController.swift

🔐 close # 87
닉네임, 나이, 병원즐겨찾기 모두 입력값을 받을 수 있게 했습니다.
나이는 0~99세로 제한을 주는게 아닌 정수값을 받을 수 있게했습니다. 
나머지 구현된것들은 이슈당 한개씩 올리겠습니다. 
SceneDelegate에서
let testVC = UINavigationController(rootViewController: ProfileViewController())
로 바꿔서 확인하시면 됩니다.

[D1] TextField구현

---

IKU/IKU/Views/ProfileViewController.swift
IKU/IKU/Views/StoryView.swift

🔓 open #88 
프로필 화면에서 닉네임 글자수 제한을 뒀습니다,
7글자인줄 알고 커밋할때 limitLength = 7로 두었는데 10으로 두고 바로 다시 커밋 날리겠습니다.

[D1] 닉네임 글자수 제한

---

IKU/IKU/Views/ProfileViewController.swift
IKU/IKU/Views/StoryView.swift

🔐 close #
🔓 open #54  
사시검사 뷰에서 우측 상단에 있는 아이사진을 누르면 프로필뷰로 넘어갑니다!

[D1] 아이 사진을 누르면 프로필뷰로 연결

---

IKU/IKU/Extension/UIViewController+Extension.swift
IKU/IKU/Storyboard/Base.lproj/Main.storyboard
IKU/IKU/Views/HistoryListViewController.swift
IKU/IKU/Views/ResultViewController.swift

🔐 close #113
🔐 close #114
- 검사를 기록을 리스트 형식으로 확인할 수 있습니다.

[D1] 기록을 리스트 형식으로 확인할 수 있습니다.

---

IKU/IKU/Views/HistoryListViewController.swift
IKU/IKU/Views/HistoryViewController.swift
IKU/IKU/Views/ResultViewController.swift

🔐 close #116
🔐 close #118
- 쓰레기통 아이콘을 통해 결과를 삭제할 수 있습니다.

[D2] 쓰레기통 버튼을 누르면 기록이 삭제된다

---

IKU/IKU/Views/ScrubberView.swift

🔐 close #133 
- 시작시 ScrubberView가 정 가운데에 있습니다.
- ScrubberView가 Video 전체를 담도록 하여 더 이상 화면 밖의 영상을 선택하지 않습니다.
- 사시검사 탭에서 검사 후 사진 선택 화면에서 ScrubberView를 만져보면 됩니다.
- 남는 공간은 이미지를 잘라 붙이는 방법으로 해결하였습니다.

[D1] ScrubberView가 정확한 위치를 가리키고, 전체 Video를 담도록 수정

---

IKU/IKU/Views/HistoryListViewController.swift
IKU/IKU/Views/ResultViewController.swift
IKU/IKU/Views/ViewModule/IKUCalendarView/CVCalendar/CVCalendarDayView.swift

🔐 close #120
🔐 close #121
🔐 close #122
- 결과 화면에서 북마크 설정/해제 할 수 있습니다.
- 북마크한 결과가 있는 날에 북마크가 표시가 됩니다.
- 리스트 화면에서 북마크된 결과만 필터링할 수 있습니다. 
- 검사 후 북마크 기능을 이용하여 테스트 할 수 있습니다.

[D2] 북마크 기능을 사용할 수 있습니다.

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/Views/CoverTestViewController.swift
IKU/IKU/Views/NavigationViewController.swift
IKU/IKU/Views/ScrubberView.swift
IKU/IKU/Views/SelectPhotoViewController.swift
IKU/IKU/Views/SpeechBubbleView.swift

🔐 close #5
🔐 close #152
- Frame을 추천해주는 기능을 추가하였습니다.
- 직전 화면에서 추천 Frame으로 자동 이동
- 다른 Frame에서 추천 Frame 터치시 부드럽게 애니메이션 되면서 이동함
- 추천 Frame 위에 Recommended Frame 말풍선 올려주기
- 다른 Frame에서 Recommended Frame 말풍선이 사라지는 기능은 구현하지 못하였습니다.
- 하단 Frame을 Scrubbing 하고 있을 때 play button이 떠있는 문제도 함께 해결하였습니다.
- 검사 후 추천 frame으로 자동 이동하는지 확인
- 다른 frame에서 추천 frame(노란색으로 하이라이팅 됨)을 터치시 부드럽게 이동하는지 확인
- play button이 떠 있는 상태에서 하단 scrubbing view를 드래그시 play button이 사라지는지 확인

[D1] Frame 추천 기능

---

IKU/IKU/Views/ProfileViewController.swift

- ProfileView의 Navigation Title을 추가하였습니다.

[D1] Navigation Title in ProfileView

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/Storyboard/Base.lproj/Main.storyboard
IKU/IKU/Views/HistoryViewController.swift
IKU/IKU/Views/ResultViewController.swift
IKU/IKU/Views/ScrubberView.swift
IKU/IKU/Views/SelectPhotoViewController.swift

🔐 close #172 
- 동영상 다시 보기 버튼을 만들었습니다
- 검사 화면에서는 다시 보기 버튼이 없어야 합니다.
- 기록 화면에서 넘어갈 때에 다시 보기 버튼이 있어야 합니다.
- 다시 보기를 눌렀을 때 하이라이트된 부분이 없어야 합니다.
- 검사 화면에서 검사 완료 후 replay 버튼이 없는 것을 확인한다.
- 검사가 완료 된 개별 기록에서 replay를 누른다.

[D1] 동영상 다시 보기 버튼

---

IKU/IKU.xcodeproj/project.pbxproj
IKU/IKU/Data/StrabismusLog.swift
IKU/IKU/Data/TestGuideString.swift
IKU/IKU/Extension/UIViewController+Extension.swift
IKU/IKU/Views/CareGuideView.swift
IKU/IKU/Views/CoverTestViewModel.swift
IKU/IKU/Views/HistoryListViewController.swift
IKU/IKU/Views/ProfileViewController.swift
IKU/IKU/Views/ResultViewController.swift
IKU/IKU/Views/SelectPhotoViewController.swift
IKU/IKU/Views/StoryView.swift
IKU/IKU/Views/ViewModule/IKUChartView.swift

🔐 close #171 
- 피그마 내용에 따라 영어문구를 검토 및 수정하였습니다.
- 몇가지 UI가 수정되었습니다.
- Chart에 0.5~1.0 의 값이 표시됩니다.
- 5.0 값에 기준선이 추가되었습니다.

[D1] 영어문구 수정 및 UI 변경

---

IKU/IKU/Views/ViewModule/IKUChartView.swift

🔐 close #181 
- Chart의 Title 문구를 변경하였습니다.

[D0] Chart Title 문구 변경

---

IKU/IKU/Views/WhatIsCoverTestView.swift

🔐 close #186 
- What is Cover Test 의 6, 8번 사진을 정상적으로 표시합니다.
- What is Cover Test의 6, 8번 사진을 확인합니다.

What is Cover Test의 6, 8번 사진을 정상적으로 표시합니다.

---

IKU/IKU/Views/ResultViewController.swift

🔐 close #188 
- 결과 화면을 수정하였습니다.
- 문구의 개행을 수정하였습니다.
- 결과에 따라 잘못표시되고 있는 로직을 해결하였습니다.
- 결과 화면에 진입하면됩니다.

[D0] 결과화면 오류 수정

---

README.md

- [확인하러 가기](https://github.com/DeveloperAcademy-POSTECH/MacC-Team-IKU/tree/README.md)
- 앱 아이콘 안 보이는 현상 해결
- 날짜 볼드 처리
- Media 내용 추가
- TestFlight Link 추가
- 1번 스크린샷 변경
- Demo gif 추가
- Thank you for concern 이상해 보여서 변경
**참고 : 피그마 링크는 안 넣었습니다. 의견 주세요.**

[D3] README.md 수정
